# ----
# Site

title: ZatpatPay - Fast, Easy, Transparent.
url: 
baseurl: 
google_analytics_key: UA-102992451-1
google_maps_javascript_api_key: AIzaSyBygx1Dl5wxUsGb7kCi9HAHzznQ7qOVQ2g
disqus_shortname: zatpatpay

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description:
author:
  name:
  email:
  twitter:
social:
  name: ZatpatPay
  links:
    - https://zatpatpay.com

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: ZatpatPay - Fast, East and Transparent
  blurb: ZatpatPay, making transactions faster for the merchants, easier for the customers, transparent and inexpensive for all.
